"""Add status column to Address table

Revision ID: 3d3a02b96a85
Revises: 43005307fe7e
Create Date: 2025-03-03 12:34:42.389056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3a02b96a85'
down_revision: Union[str, None] = '43005307fe7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('status', sa.String(length=20), server_default='active', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'status')
    # ### end Alembic commands ###
